# Generated by Django 4.1.4 on 2022-12-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='patronymic',
        ),
    ]
